### ISSUE TITLE
Guides site down

### ISSUE THREAD

**Issue by skitterm** [emberjs/guides#2122] opened 2017-11-09 00:25 UTC
The "guides" portion of the Ember website has been down for a few hours. Here's what I see when going to the site on Firefox:

![screenshot](https://user-images.githubusercontent.com/5875149/32581981-470f137e-c4a1-11e7-9412-12ca8d9cc897.PNG)

**Comment by locks** [comment] 2017-11-09 06:09
Thanks for reporting. I cannot reproduce this now, and I was using the Guides late last night without any issues, so I'm unsure what might be happening here.
Can you provide more info on why the certificate is invalid?

**Comment by skitterm** [comment] 2017-11-21 01:02
After being fine for awhile, it's been down again for me now for the past 2 hours. 
![capture](https://user-images.githubusercontent.com/5875149/33045828-216b9a0a-ce03-11e7-9ec6-2ad94b987147.PNG)

**Comment by locks** [comment] 2017-11-21 01:04
Do you have problems with other websites? DNS issues, corporate firewall/blocker? I still can't reproduce :/

**Comment by skitterm** [comment] 2017-11-21 01:10
Other sites come thru fine for me. 

I do get the "i" icon in the URL bar which, when clicked on, says "connection is not secure", and on viewing more info, gives this message:

![issue](https://user-images.githubusercontent.com/5875149/33049536-753699b6-ce15-11e7-8446-c40dd8600c94.PNG)

Ember js [homepage](https://www.emberjs.com/) loads fine and has the green lock icon in the URL bar.

**Comment by acorncom** [comment] 2017-11-21 05:07
@skitterm we use Netlify for hosting the guides pages but Heroku for the main website. Do you have the same trouble when visiting https://www.netlify.com/ ? Could you give us any additional details on OS version? Do you have the same troubles with other browsers? What version of Firefox are you using? 

Would love to help track things down, so any/all info you can give us would be greatly appreciated.

**Comment by skitterm** [comment] 2017-11-21 23:59
I am able to see the netlify site just fine (though the guides are back up, so I'll check that site the next time they're down).

I've seen the problem on Chrome 63 and Firefox 57, both on Windows 8.1.

**Comment by skitterm** [comment] 2017-11-22 17:14
The guides is down again; I went to netlify and that site is also down for me.

**Comment by skitterm** [comment] 2017-11-22 17:17
Here's the message on IE:
![iemessage](https://user-images.githubusercontent.com/5875149/33140777-d1d13efa-cf65-11e7-93c8-ff39e6f59004.PNG)

I'm getting the guides on my phone, so for me it's just a desktop issue.

**Comment by MelSumner** [comment] 2017-12-05 16:21
I can't reproduce this issue. @skitterm is this still an issue for you?

**Comment by skitterm** [comment] 2017-12-05 17:48
It is right now... hasn't been for a few days, until now. I can't see netlify site either.

Feel free to close if I'm the only one seeing this :)

**Comment by acorncom** [comment] 2017-12-08 06:00
@skitterm one last question, but then yes, we may end up needing to close this. Are you running into this at your work? Do you happen to see the same issues elsewhere?  Is it just one desktop you're seeing it on or do you find it's a problem with multiple machines you use regularly in different places?  Sounds like it could be a network / corporate environment issue of some kind ...

**Comment by skitterm** [comment] 2017-12-08 17:14
I am seeing this at work. Once when it was down on my work workstation, I looked at the guides on my phone and they showed up. Presumably I was on a different network.

Looks like it's a combination of Netlify and the internal network (I've never noticed this issue accessing other sites from work).

**Comment by locks** [comment] 2018-01-16 13:13
I am sorry that you are having this problem, but I am not sure what we could do besides moving to another host :/ I hope you are still able to access the documentation using another browser or similar!

**Closed by locks** 2018-01-16 13:13 UTC
