### ISSUE TITLE
Tutorial: application stops working after "Updating the model hook"

### ISSUE THREAD

**Issue by newton3** [emberjs/guides#1847] opened 2017-03-17 21:31 UTC
I am new to ember and trying to follow along with the tutorial.
At one point it just stops working and I have no clue what an 'store' actually is
[https://guides.emberjs.com/v2.11.0/tutorial/ember-data/#toc_updating-the-model-hook](url)
has anyone faced the same issue or can help me? Not sure if this is a duplicate.

**Comment by toddjordan** [comment] 2017-03-18 01:01
Hi @newton3 thanks for reporting.  can you give any detail on what happens when it stops working?
Any errors in the console, any description of what the screen looks like?

**Comment by toddjordan** [comment] 2017-03-18 01:14
also, there's a working version of the tutorial app here: https://github.com/ember-learn/super-rentals

**Comment by newton3** [comment] 2017-03-20 21:28
Thanks. I would refer to the working version and try to figure out the details with documentation.

**Comment by thomaswelton** [comment] 2017-03-21 14:04
Kinda weird. For me this page was going to a 404 https://guides.emberjs.com/v2.12.0/tutorial/model-hook/ either when clicking on the side nav or clicking on when clicking the link in the footer of the previous section.
However now both seem to be fine. Sorry if that's not clear steps to reproduce.

**Comment by toddjordan** [comment] 2017-03-21 14:38
@thomaswelton see https://github.com/emberjs/guides/issues/1858
there have been some cdn issues today with the website

**Comment by toddjordan** [comment] 2017-03-22 12:54
Closing this issue out for now.

**Closed by toddjordan** 2017-03-22 12:54 UTC
Labels: needs submitter response
