### ISSUE TITLE
Expose the latest guides without a version number for SEO

### ISSUE THREAD

**Issue by aortbals** [emberjs/guides#604] opened 2015-08-17 17:05 UTC
One thing I've noticed with the recent edition of versioned guides is that Google is surfacing older guides at the top of search results because all guide URLs are versioned. I would like to propose that the guides adopt a URL structure where the latest stable release has a constant URL as well as a versioned URL. This seems to work well for Rails Guides. A few options:

- http://guides.emberjs.com/
- http://guides.emberjs.com/stable/

would return the content (currently) for Ember 2.0 without a redirect.

This could also work with "Edge" or canary guides:

- http://guides.emberjs.com/edge/
- http://guides.emberjs.com/canary/

**Comment by locks** [comment] 2015-08-17 21:51
I may be mistaken, but this would necessitate a re-architecting of the application which at the moment is a tricky proposition.

**Comment by acorncom** [comment] 2015-08-17 23:07
@locks What web server is running things behind the scenes?  I'm coming from a Nginx / Apache background, but I believe that type of rewrite would be possible with RewriteRules for those servers ...  Seems like it'd involve a look up of which version was current in our `version.json` file?

**Comment by locks** [comment] 2015-08-18 00:09
@acorncom divshot

**Comment by acorncom** [comment] 2015-08-18 00:47
@locks Would the custom redirects mentioned at https://docs.divshot.com/guides/routing do what we're after?  Seems like we could setup 301 redirects in our config file (though we'd have to change the config file during each deploy ...)

**Comment by michaelrkn** [comment] 2015-08-18 05:24
I like this idea! It will require a big re-architecting of the application however.

**Comment by locks** [comment] 2015-08-19 10:03
![screen shot 2015-08-19 at 11 01 19](https://cloud.githubusercontent.com/assets/32344/9353640/c0f1e25e-4661-11e5-842a-27082877b96b.png)

Hm, we already do a 302. I don't think a 301 is the right status here, since we will be constantly changing it with each new release.

**Comment by acorncom** [comment] 2015-08-20 13:04
@locks Good point about the 301 vs 302.  Guess I was thinking that a redirect from 'stable' to '2.0.0' might be able to be setup though ...  Think it's doable?

**Comment by leo** [comment] 2015-11-28 12:03
Can we please find a solution for this? :blush:

It's so annoying to always get results for `1.10.0` rather than for the latest version. Even when searching for something like "ember 2 routing", you'll still get the docs for `1.10.0` at first.

**Comment by michaelrkn** [comment] 2015-12-04 04:33
On the docs team call today, we agreed on a solution for this, along the lines proposed by @rtablada. Here's how it should work, more or less:

* When we deploy, we copy the most recent build into `/2.x.x` as well as `/current`. This could probably be automated by updating https://github.com/emberjs/guides.emberjs.com/blob/master/tasks/update-versions.js.
* When a page in the Guides is renamed, moved to another section, or deleted, an entry needs to be added to https://github.com/emberjs/guides.emberjs.com/blob/master/divshot.json (which will soon become [firebase.json](https://www.firebase.com/docs/hosting/guide/url-redirects-rewrites.html). This means we should probably move that file into this repo, so that it can be part of the same commit in which a page is removed. (Otherwise we will lose track of the change and not update the redirects.)
* We need to add something to the build process to automate checking for pages that have been removed, ensuring that there is an appropriate redirect in place, and failing the build if there is not.

**Comment by rtablada** [comment] 2015-12-04 04:54
@michaelrkn :+1: for the idea of build check for failing builds if no redirect or substantial replacement is listed.

**Comment by mozeryansky** [comment] 2015-12-31 06:55
Could /current just be a page with a js redirect which opens http://guides.emberjs.com/versions.json gets the latest version then redirects to that url? One file and done.

**Comment by mozeryansky** [comment] 2015-12-31 06:56
More like do a redirect with /current/ replaced with the version number so all urls work.

**Comment by acorncom** [comment] 2016-07-29 23:50
Re: https://github.com/emberjs/guides/issues/604#issuecomment-168137300, confirmed, that is the plan. I'm going to close this in favor of #1185

**Closed by acorncom** 2016-07-29 23:50 UTC
Labels: help wanted, infrastructure
