### ISSUE TITLE
Tutorial stops working when Mirage is introduced

### ISSUE THREAD

**Issue by ChrisMiami** [emberjs/guides#1191] opened 2016-01-24 21:35 UTC
This may be user error, but I have done what I can to try to find it and cannot.

Going through the tutorial page-by-page (including installation from scratch on a new OS X box) leaves me with a non-functioning app when I complete this page: https://guides.emberjs.com/v2.3.0/tutorial/ember-data/ . Presumably, the data is supposed to display in place of the non-mirage version that was previously working.  It doesn't. Nothing renders in that space.

In the web console, I see a lot of errors about findAll being deprecated, and then I see the data that's returned, looking just like it should, and then a warning about "data" not finding "datum" in the model.

I tried playing with names and pluralizations (it seemed strange that the `type:'rentals'` would not be `type:'rental'` for each individual entity), but eventually I managed to make the app completely broken.  As a newbie, I have no clue what to look at to fix it, so I'm pretty much DIW (dead in the water).

[Edit; tried to upload the super-rentals folder but 47000 items makes a file bigger than GitHub will accept. Adding just app/ instead.]
[app.zip](https://github.com/emberjs/guides/files/102555/app.zip)

**Comment by locks** [comment] 2016-01-24 22:57
From the deprecation and the `data` error message, I believe this is a duplicate of: https://github.com/emberjs/guides/issues/1149 https://github.com/emberjs/guides/issues/1062 https://github.com/emberjs/guides/issues/1119

Check the linked threads and if you continue having problems, reach out to us at #documentation or #needhelp on Slack!

**Closed by locks** 2016-01-24 22:57 UTC

**Comment by ChrisMiami** [comment] 2016-01-26 17:20
Thank you @locks - I followed the steps in the upgrading guide referenced by #1149.  Since all this is fresh install for me, I think instead of a *"oh, by the way, just in case"* type of section, that upgrade should be a ***"This is a Mandatory First Step"*** - until the npm installer gets fixed to install the latest version.

So, `npm install bower` is not useful, but you have to add the -g: `npm install -d bower`.
Then update the file.
Then `bower install` and THEN you get a bunch of hogwash on the terminal about versiony things, and it asks you to make a choice:
```
Unable to find a suitable version for ember, please choose one:
    1) ember#>= 1.8.1 < 2.0.0 which resolved to 1.13.13 and is required by ember-data#1.13.15
    2) ember#>=1.4 which resolved to 2.3.0 and is required by ember-cli-shims#0.0.6
    3) ember#> 1.5.0-beta.3 which resolved to 2.3.0 and is required by ember-resolver#0.1.21
    4) ember#2.3.0 which resolved to 2.3.0 and is required by super-rentals
    5) ember#^2.0.0 which resolved to 2.3.0 and is required by ember-data#2.3.0

Prefix the choice with ! to persist it to bower.json

? Answer !4
bower ember                        resolution Saved ember#2.3.0 as resolution
bower ember-data#2.3.0                install ember-data#2.3.0
bower ember#2.3.0                     install ember#2.3.0

ember-data#2.3.0 bower_components/ember-data
└── ember#2.3.0

ember#2.3.0 bower_components/ember
└── jquery#1.11.3
```
I chose 4 and added the '!' so it'd persist it (whatever that may entail).

Then, I ran the server and navigated to the URL and still got a blank page.
```
$ ember s
version: 1.13.15
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

I will review the other linked issues.  Were you able to review my files?  Did I mess up the contents somehow?  Do they run when dropped onto your super-rentals?

In the end, I think the tutorial needs to be cleanly followable which given my (and apparently others') experience(s), it is not.

**Comment by ChrisMiami** [comment] 2016-01-26 17:21
By the way, I don't think you should close this issue until a new tutorial is published on the site, but that's just my opinion.

**Comment by locks** [comment] 2016-01-26 17:24
An update was published to the website, in [Installing Ember](https://guides.emberjs.com/v2.3.0/getting-started/#toc_installation) we now direct people to install the beta, avoiding the version mismatch.
There are further improvements on the pipeline to make it clearer, we'll release them as soon as they get merged.
