### ISSUE TITLE
Wrong / Duplicate code example in Models/PersistingRecords

### ISSUE THREAD

**Issue by tryggve** [emberjs/guides#459] opened 2015-07-22 12:44 UTC
http://guides.emberjs.com/v1.13.0/models/persisting-records/

The second code example under the Promises topic is wrong.
It should show how to work with failed network requests.
It is showing how to handle success and failure scenarios.

**Comment by michaelrkn** [comment] 2015-07-22 14:20
Thanks for opening this issue! Could you suggest what the code should be? Or better yet, open a PR?

**Comment by tryggve** [comment] 2015-07-27 09:53
Hi,

As I'm a Ember newbie I don't think I'm currently the person to contribute
with this kind of material. I assumed you had the missing example stashed
away somewhere in the git history and it would be a quick matter to resolve.

Regards
Tryggve

2015-07-22 16:21 GMT+02:00 Michael Kaiser-Nyman <notifications@github.com>:

**Comment by michaelrkn** [comment] 2015-07-27 14:58
@locks can you confirm this is an issue, and if so, maybe work on while you tackle #449?

**Comment by locks** [comment] 2015-07-29 19:41
I don't understand what the problem is @tryggve, do you mean that the failure handler should have code inside it? If there is a network failure then the promise will trigger the onFail handler.

**Comment by tryggve** [comment] 2015-08-03 22:34
So the only difference between the first and second example regarding
promises is row 16? It seems to me as the first and second example is the
same example, which both describe the first scenario, how to handle success
and failure when trying to resolve a promise.

You are correct in that, if there is a network failure, the onFail method
will be called, I just don't see how it is helping anyone who has already
read the first example which will do the same thing.

If you look at the API spec for the catch method of the RSVP.Promise
<http://emberjs.com/api/classes/RSVP.Promise.html#method_catch> class it
states that "catch is simply sugar for then(undefined, onRejection) which
makes it the same as the catch block of a try/catch statement.".

This made me think that something was wrong, since the both examples does
the same thing and looks the same and has the same code even. If all is in
order then there is nothing more to do but close this issue and move along.

Regards
Tryggve

2015-07-29 21:41 GMT+02:00 Ricardo Mendes <notifications@github.com>:

**Comment by michaelrkn** [comment] 2015-08-22 18:34
Closing since this will be addresses in #449.

**Closed by michaelrkn** 2015-08-22 18:34 UTC
