### ISSUE TITLE
Search results have unversioned links

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#514] opened 2015-08-02 05:12 UTC
1. Go to http://guides.emberjs.com/. 
2. Type a term like "Ember" in the search box. Don't press the down arrow key. Press Enter. A modal opens.
3. Click a link. 

Expected behavior: You are taken to a URL with the version number, eg http://guides.emberjs.com/v1.13.0/getting-started/. 

Actual behavior: You are taken to a URL with the version number, eg http://guides.emberjs.com/getting-started.

This issue is not present if you enter a search term, use the down arrow to navigate through the results, and press Enter.

This issue is present in the 1.13 and 1.12 guides, making me think (/hope) that I did not introduce it myself when updating search.

Versions 1.10 and 1.11 of the guides simply refresh the page when you press Enter without pressing the down arrow... I'm not sure what's going on there.

**Comment by michaelrkn** [comment] 2015-08-02 05:12
@trek do you have any idea what's going on here?

**Comment by acorncom** [comment] 2015-08-10 23:51
What seems to be happening is that the `onComplete` handler is properly fired when directly using the `Swiftype` [autocomplete plugin](https://github.com/swiftype/swiftype-autocomplete-jquery/blob/master/jquery.swiftype.autocomplete.js) here:

https://github.com/emberjs/guides/blob/master/source/javascripts/swiftype.js.erb#L29-31

Specifically, the callback we're registered is located [here in the plugin](https://github.com/swiftype/swiftype-autocomplete-jquery/blob/master/jquery.swiftype.autocomplete.js#L163-165)

However, when we open up the "search results" box, we shift to using a second Swiftype plugin for [handling search](https://github.com/swiftype/swiftype-search-jquery).  Looking through that plugin, there doesn't seem to be a callback we can use like we're doing right now.  This would be the logical location for it it looks like:

https://github.com/swiftype/swiftype-search-jquery/blob/master/jquery.swiftype.search.js#L54-62

I'll open an issue and see if they are open to tweaking that function.

**Comment by michaelrkn** [comment] 2015-08-11 04:51
Thank you for your sleuthing @acorncom!

**Comment by qhoxie** [comment] 2015-08-11 05:38
Hey guys,

This seems like a logical extension to the plugin.  We'll take a look at it ASAP.

Best,
Quin / Swiftype

**Comment by michaelrkn** [comment] 2015-08-30 19:17
Hey @qhoxie - any word on this? Thanks!

**Comment by anthias** [comment] 2015-08-31 17:01
Hey @michaelrkn. I posted this PR https://github.com/swiftype/swiftype-search-jquery/pull/20. Does that change work for you? If so, I'll release ASAP.

**Comment by michaelrkn** [comment] 2015-08-31 20:25
Awesome! Looks good to me. If I understand right, this will let us do:

```js
$(function() {
  var defaultOnComplete = function(elem) {
    window.location = '/' + currentRevision + elem.attr('href');
  };

  $('#st-search-input').swiftype({
    engineKey:  '<%= data.search.engine_key %>',
    searchFields: Swiftype.searchSearchFields,
    fetchFields: Swiftype.searchFetchFields,
    documentTypes: Swiftype.searchDocumentTypes,
    onComplete: onComplete
  });
});
```

If so, that will work perfectly.

**Comment by anthias** [comment] 2015-08-31 20:58
Great. I just merged it. One note on your code above, I believe you'll need to change `var defaultOnComplete = function` to `var onComplete = function`. Otherwise onComplete will be undefined.

**Comment by michaelrkn** [comment] 2015-09-01 00:16
Thank you!!

@acorncom want to keep going with getting this implemented in the Guides?

**Comment by acorncom** [comment] 2015-09-01 00:18
@michaelrkn Thought I could yes.  Might have time tomorrow.  If someone else beats me to it I won't complain though, would like to see this fixed! :-)

**Comment by acorncom** [comment] 2015-09-30 15:27
@michaelrkn Not sure if you know anyone else who can whip this out prior to the merge this weekend.  I'd hoped to get it done (it's been on the list for the last month), but I'm headed out to a business conference today and won't be able finish it off before the merge window :-/

**Comment by michaelrkn** [comment] 2015-09-30 15:34
I just put a call for help in the docs Slack channel.

**Comment by kevinkucharczyk** [comment] 2015-10-01 12:54
I did some digging and I think this issue doesn't have much to do with the [search plugin](https://github.com/swiftype/swiftype-search-jquery) after all.

What's happening is: we are [including the Swiftype Widget](https://github.com/emberjs/guides/blob/master/source/javascripts/app/swiftype.js.erb#L20-L25) by adding a Swiftype embed.js script. This script will then proceed to add further Swiftype scripts and stylesheets, which are all part of their Search Widget.

It turns out that this method is [a bit outdated](https://swiftype.com/documentation/tutorials/upgrade_to_search_widget_designer) and that there are new options to include it. The widget that's used in the Gudies will add a Submit handler on the form where our search input field is located - this opens a search overlay/modal box with the results. Now these results are simple `<a>` links generated from a template. Unfortunately there doesn't seem to be any exposed [configuration](https://swiftype.com/documentation/legacy_widget_options) for these templates.

This also explains why the page was getting refreshed in older versions of the guide: the Swiftype embed code was not present, so the search input form didn't have any custom handlers - it acted like a regular HTML form.

Now I'm not quite sure how to solve this issue. We could try using the new Search Widgets, but this requires logging in to Swiftype and doing some configuration from their dashboard. We could also add a hacky script that adds a version prefix to the urls in the modal, after it's been displayed. Lastly, we could add the swiftype-search-plugin and use it to build a custom modal of our own.

**Comment by kevinkucharczyk** [comment] 2015-10-01 17:09
![screenshot-swiftype com 2015-10-01 18-25-49](https://cloud.githubusercontent.com/assets/3127419/10227369/35341c5e-686d-11e5-93c8-fd6a32729865.png)

So we've tried using the Swiftype dashboard to configure the widget (thanks to @michaelrkn for helping out here!). Unfortunately, since the Guides contain multiple Document Types (one for each Guides version), it is not possible to use the new widget.

Does anyone have any ideas on how to continue here?

We could try and recreate the modal ourselves, or modify the scripts that are being sideloaded and include them ourselves.

Another option would be something hacky to modify the modal links whenever they appear (adding the currentRevision variable to the links), along these lines:
```
$(document).on('DOMNodeInserted','.st-result',function() {
  var searchElement = $(this).find('h3');
  var searchLink = $(this).find('a.st-search-result-link');
  var searchUrl = currentRevision + searchElement.data('dest-url');
  searchElement.attr('data-dest-url', searchUrl);
  /*
    Swiftype seems to be listening to clicks and
    redirecting to the url in the data attribute above
  */
  searchLink.attr('href', searchUrl); // just in case
});
```
But this just feels wrong.

**Comment by qhoxie** [comment] 2015-10-01 17:12
Hi everyone,

Quin from Swiftype here.  I'm going to loop in some folks from our team to see how we can help get this sorted out.

Best,
Quin

**Comment by michaelrkn** [comment] 2015-10-01 18:12
Since we're currently using multiple content types, which seems to be discouraged, maybe we should look at another way to structure our data? It might be a pain to go back and re-architect our search for past versions, but it sounds like it's going to be a pain no matter what ;)

Since we are releasing this Sunday, we might need to go the dirty hack route for now, and then figure out and implement the "right" way for the 2.2 release.

**Comment by kevinkucharczyk** [comment] 2015-10-01 18:45
Maybe @qhoxie will come back with something useful soon. If not, I can open a PR with the hacky solution tomorrow or Saturday.

**Comment by anthias** [comment] 2015-10-01 19:58
Hey Guys,
I took a look at your configuration. I think the best way forward is to keep the javascript you're already using and modify it to consider version numbers like below:

The code below changes the document type to search over based on `window.currentRevision`. It looks like that's the correct variable to use.
``` javascript
Swiftype.searchDocumentTypes = function(){
  return ['guides-'+currentRevision.replace(/\./g, '-')];
};
```

The function below overrides the url used for result clicks. The version number is missing from the url field now, which is why clicks aren't working.
``` javascript
Swiftype.Util.getUrlFromItem = function(item){
  return '/'+currentRevision+item['url'];
};
```

The code above should be loaded after the normal Swiftype javascript.
 
I think this will resolve your issues. Sorry for not identifying it earlier. When I first looked into this problem the overlay wasn't working and I assumed you were using our jQuery plugin based on the conversation.

Let me know if you have any more questions.

Thanks,
    jeff

**Comment by kevinkucharczyk** [comment] 2015-10-02 08:20
Thank you for your help, @anthias!

Unfortunately, overriding the `getUrlFromItem` function doesn't seem to have any effect. I think the search overlay is rendered using the request data directly - so the urls are populated just as they are received from the server.

Furthermore, I don't know how we could execute code after Swiftype has loaded - we are appending embed.js, which again is appending a couple of other sources - is there a sensible way to determine when the sources from embed.js are loaded, in order for us to execute more JS?

**Comment by michaelrkn** [comment] 2015-10-08 20:19
Hey @anthias - just wanted to ping you on this. We're using a hacky workaround for now, but if you have any insight into @kevinkucharczyk's comment above, we'd be really grateful!

**Comment by acorncom** [comment] 2015-10-08 23:36
I hate to even suggest this, but would shifting to a different search system help us at all?  I've been using Algolia for a few other jobs and it's pretty powerful.  Believe it's free for open source projects (but would take some work to shift everything over ...)

**Comment by locks** [comment] 2015-10-08 23:49
@acorncom I don't think so, because part of the problem is that each version of the Guides it's its own site, thus being fixed in 2.0 / 2.1.0 [afaik].

**Comment by anthias** [comment] 2015-10-09 01:41
Hey Guys. I'm looking into this. Search doesn't work for me locally either. Is this a know issue? Is there a way to seed the version number?

**Comment by kevinkucharczyk** [comment] 2015-10-09 07:52
@anthias just set the currentRevision variable to 'v2.1.0' in https://github.com/emberjs/guides/blob/master/source/javascripts/app/swiftype.js.erb - this should enable search.

**Comment by anthias** [comment] 2015-10-13 23:49
Hello everyone. I added the pull request above to resolve this issue. Please let me know if it works for you.

**Closed** 2015-10-14 17:11 UTC
Labels: infrastructure
