### ISSUE TITLE
reference to nonexistent acceptance test in image at end of 'Services and Utilities' section of tutorial

### ISSUE THREAD

**Issue by nateq314** [emberjs/guides#1930] opened 2017-04-28 19:15 UTC
The acceptance test shown in the image at the end of this section ("should initially list 3 rentals") hasn't actually appeared anywhere in the tutorial up to this point. The component integration test `list-filter-test.js` does test that the component 'should initially load all listings'. Is that what should be displayed instead? Or perhaps the acceptance test displayed in the image should be added into the tutorial content?

**Comment by toddjordan** [comment] 2017-04-28 19:30
Hi, thanks for reporting.  its introduced here: https://guides.emberjs.com/v2.12.0/tutorial/model-hook/#toc_acceptance-testing-the-rental-list .   

In the services and utilities section we are just mocking the service so maps don't show up in the acceptance tests.

It could be cleaned up a bit to be clearer, i.e. refer back to where its introduced.

**Comment by toddjordan** [comment] 2017-05-18 16:42
Closing as a duplicate of issue #1665

**Closed by toddjordan** 2017-05-18 16:42 UTC
Labels: good for new contributors, help wanted, tutorial
