### ISSUE TITLE
Custom 404 page not being served, get Divshot generic 404 page

### ISSUE THREAD

**Issue by eliotsykes** [emberjs/guides#318] opened 2015-05-23 14:19 UTC
http://guides.emberjs.com/page-does-not-exist serves the Divshot generic 404 page. Expected to see the page from `guides/source/404.html.erb`

**Comment by michaelrkn** [comment] 2015-07-13 05:14
This is true. @trek do you have any ideas about this? cc @locks

**Comment by locks** [comment] 2015-07-13 12:39
Have the docs been deployed since that change got merged in?

**Comment by michaelrkn** [comment] 2015-07-13 13:31
@locks What was the change? Is there a PR you can reference?

**Comment by locks** [comment] 2015-07-13 13:57
@michaelrkn oh I thought it was this change https://github.com/emberjs/guides/commit/5daf4846b23127fa539a5db22b7c1714be387291 ?

**Comment by michaelrkn** [comment] 2015-07-13 14:00
No, that just changes the text when the custom 404 is shown. Except it seems that it is never shown.

It [looks like](https://github.com/divshot/superstatic#configuration) we can provide a `superstatic.json` configuration file with an `error_page` key pointing to `404.html` to get it served properly. @trek do you know if we can simply put that file in the `source` folder?

**Comment by rwjblue** [comment] 2015-07-13 14:05
> It looks like we can provide a superstatic.json configuration file with an error_page key pointing to 404.html to get it served properly.

Seems like that is already setup [here](https://github.com/emberjs/guides.emberjs.com/blob/master/divshot.json#L5).

**Comment by michaelrkn** [comment] 2015-07-13 14:09
Hrm, then it seems it isn't working properly.

**Comment by michaelrkn** [comment] 2015-07-13 14:49
Maybe the problem is that 404.html is nested within the version number? Should it be copied into the root of https://github.com/emberjs/guides.emberjs.com?

**Comment by trek** [comment] 2015-07-14 13:12
I believe yes, we'd need the 404 page as part of https://github.com/emberjs/guides.emberjs.com

**Comment by michaelrkn** [comment] 2015-07-17 17:57
@trek is this something I can help out with? How do we get 404.html into that root as part of the build process? Or should we just move it out of this repo and into https://github.com/emberjs/guides.emberjs.com?

**Closed** 2015-07-21 23:52 UTC
