### ISSUE TITLE
Ember install 2.6 and Quick Guide

### ISSUE THREAD

**Issue by NegativeIQ** [emberjs/guides#1527] opened 2016-06-22 20:48 UTC
Hey guys, just started learning Ember and i already love it, but i run into a few problems at the very start. Fist, Ember install 2.6 is missing default application.hbs and guide actually depends on its existence and containing {{outlet}} inside it for other routes to work, actually to show up.
Also we need to remove welcome page from npm (package.json) dependency, but its not mentioned in guide and its also easy to miss on that start page, i know i almost did.

**Comment by locks** [comment] 2016-06-22 23:14
Hi @NegativeIQ, thank you for the feedback. We are aware and dealing with the issue soon, we just need to take care of some other loose ends first. 

I'm closing this as it's a duplicate of https://github.com/emberjs/guides/issues/1491 and https://github.com/emberjs/guides/issues/1498, you can track the evolution there.

**Closed by locks** 2016-06-22 23:14 UTC
